AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example basic lambda using `holy-lambda` micro library

Parameters:
  Timeout:
    Type: Number
    Default: 40
  MemorySize:
    Type: Number
    Default: 128
  Entrypoint:
    Type: String
    Default: example1.core

Globals:
  Function:
    Timeout: !Ref Timeout
    MemorySize: !Ref MemorySize
    Environment:
      Variables:
        HL_ENTRYPOINT: !Ref Entrypoint

Resources:
  ExampleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures: [arm64]
      FunctionName: ExampleLambdaFunction
      Runtime: provided.al2
      Handler: example1.core.HttpApiProxyGateway
      CodeUri: .holy-lambda/build/latest.zip
      # For docker based deployments use:
      # PackageType: Image
      # and remove Runtime + CodeUri + Handler
      Events:
        HelloEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ExampleHttpApi
            Path: /
            Method: GET
    # For docker based deployments
    # Metadata:
    #   Dockerfile: Dockerfile
    #   DockerContext: .
    #   DockerTag: v1

  ExampleHttpApi:
    Type: AWS::Serverless::HttpApi

Outputs:
  ExampleLambdaEndpoint:
    Description: Endpoint for ExampleLambdaFunction
    Value:
      Fn::Sub: https://${ExampleHttpApi}.execute-api.${AWS::Region}.amazonaws.com
